name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container: colorizenl/colorize-ci
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile
        run: gradle compileJava
      - name: Unit tests
        script: gradle coverage -Pheadless=true
