//-----------------------------------------------------------------------------
// File generated by Colorize Gradle application plugin
//-----------------------------------------------------------------------------

import SwiftUI
import WebKit

@main
struct HybridWebApp: App {
    var body: some Scene {
        WindowGroup {
            HybridWebView()
                .ignoresSafeArea()
        }
    }
}

struct HybridWebView: UIViewRepresentable {
    typealias UIViewType = WKWebView

    func makeUIView(context: Context) -> WKWebView {
        let preferences: WKPreferences = WKPreferences()
        preferences.javaScriptEnabled = true
        preferences.setValue(true, forKey: "developerExtrasEnabled")
        
        let scriptController: WKUserContentController = WKUserContentController()
        scriptController.addUserScript(WKUserScript(
            source: generateBridge(),
            injectionTime: .atDocumentEnd,
            forMainFrameOnly: false
        ))

        let config: WKWebViewConfiguration = WKWebViewConfiguration()
        config.preferences = preferences
        config.userContentController = scriptController
        config.setValue(true, forKey: "allowUniversalAccessFromFileURLs")

        let webView = WKWebView(frame: .zero, configuration: config)
        webView.scrollView.contentInsetAdjustmentBehavior = .never
        if #available(iOS 16.4, *) {
            webView.isInspectable = true
        }
        
        let scriptBridge = ScriptBridge(webView: webView)
        scriptController.add(scriptBridge, name: "openNativeBrowser")
        scriptController.add(scriptBridge, name: "loadPreferences")
        scriptController.add(scriptBridge, name: "savePreferences")
        scriptController.add(scriptBridge, name: "requestNotifications")
        scriptController.add(scriptBridge, name: "scheduleNotification")
        scriptController.add(scriptBridge, name: "cancelNotification")
        webView.navigationDelegate = scriptBridge
        
        return webView
    }
    
    func updateUIView(_ webView: WKWebView, context: Context) {
        DispatchQueue.main.async {
            let index = "HybridResources/index"
            let path = Bundle.main.path(forResource: index, ofType: "html")!
            let url = URL(fileURLWithPath: path)
            webView.loadFileURL(url, allowingReadAccessTo: url)
        }
    }
    
    func generateBridge() -> String {
        return """
            window.clrz = {
                openNativeBrowser: function(url) {
                    window.webkit.messageHandlers.openNativeBrowser.postMessage({url});
                },
                loadPreferences: function() {
                    window.webkit.messageHandlers.loadPreferences.postMessage({});
                },
                savePreferences: function(name, value) {
                    window.webkit.messageHandlers.savePreferences.postMessage({name, value});
                },
                requestNotifications: function() {
                    window.webkit.messageHandlers.requestNotifications.postMessage({});
                },
                scheduleNotification: function(id, title, preview, schedule) {
                    const message = {id, title, preview, schedule};
                    window.webkit.messageHandlers.scheduleNotification.postMessage(message);
                },
                cancelNotification: function(id) {
                    window.webkit.messageHandlers.cancelNotification.postMessage({id});
                }
            };
        """
    }
}
