#!/usr/bin/env bash

# -----------------------------------------------------------------------------
# File generated by Colorize Gradle application plugin
# -----------------------------------------------------------------------------

LAUNCHER_DIR=$(dirname "$0")

"$LAUNCHER_DIR/../PlugIns/{{jdk}}/Contents/Home/bin/java" \
    -Djava.launcher.path="$LAUNCHER_DIR" \
    -Djava.library.path="$LAUNCHER_DIR" \
    -Xmx2g \
    -Xdock:name="{{appName}}" \
    -Xdock:icon="$LAUNCHER_DIR/../Resources/icon.icns" \
    -jar "$LAUNCHER_DIR/../Java/{{jarFileName}}" {{appArgs}}
