//-----------------------------------------------------------------------------
// Gradle Application Plugin
// Copyright 2010-2026 Colorize
// Apache license (http://www.apache.org/licenses/LICENSE-2.0)
//-----------------------------------------------------------------------------

package nl.colorize.gradle.application.pwa;

import nl.colorize.gradle.application.ApplicationPlugin;
import org.gradle.api.Project;
import org.gradle.testfixtures.ProjectBuilder;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;

import static java.nio.charset.StandardCharsets.UTF_8;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class GeneratePwaTaskTest {

    private File inputDir;
    private File outputDir;
    private PwaExt config;
    private GeneratePwaTask task;

    @BeforeEach
    public void before(@TempDir File inputDir, @TempDir File outputDir) {
        this.inputDir = inputDir;
        this.outputDir = outputDir;

        Project project = ProjectBuilder.builder().withProjectDir(inputDir).build();
        project.getLayout().getBuildDirectory().set(outputDir);

        ApplicationPlugin plugin = new ApplicationPlugin();
        plugin.apply(project);

        config = project.getExtensions().getByType(PwaExt.class);
        task = (GeneratePwaTask) project.getTasks().getByName("generatePWA");
    }

    @Test
    void rewriteHTML() throws IOException {
        String html = """
            <html>
                <head>
                    <title>Test</title>
                </head>
                <body>
                    Hello world!
                </body>
            </html>
            """;

        Files.writeString(new File(inputDir, "manifest.json").toPath(), "{}", UTF_8);
        Files.writeString(new File(inputDir, "index.html").toPath(), html, UTF_8);

        config.getWebAppDir().set(inputDir.getAbsolutePath());
        config.getManifest().set(new File(inputDir, "manifest.json").getAbsolutePath());
        config.getCacheName().set("test");
        task.run(config);

        String expected = """
            <html>
                <head>
                    <title>Test</title>
                <link rel="manifest" href="manifest.json" />
            </head>
                <body>
                    Hello world!
                <script>
                const serviceWorkerSupported = typeof navigator.serviceWorker != "undefined";
                const localFile = window.location.protocol.indexOf("file") != -1;
                        
                if (serviceWorkerSupported && !localFile) {
                    navigator.serviceWorker.register("service-worker.js");
                }
            </script>
            </body>
            </html>
            """;

        assertEquals(expected, readOutput(outputDir, "pwa/index.html"));
        assertTrue(new File(outputDir, "pwa/manifest.json").exists());
        assertTrue(new File(outputDir, "pwa/service-worker.js").exists());
    }

    @Test
    void generateServiceWorker() throws IOException {
        Files.writeString(new File(inputDir, "manifest.json").toPath(), "{}", UTF_8);
        Files.writeString(new File(inputDir, "index.html").toPath(), "<head></head><body></body>", UTF_8);

        config.getWebAppDir().set(inputDir.getAbsolutePath());
        config.getManifest().set(new File(inputDir, "manifest.json").getAbsolutePath());
        config.getCacheName().set("test");
        task.run(config);

        String expected = """
            //-----------------------------------------------------------------------------
            // File generated by Colorize Gradle application plugin
            //-----------------------------------------------------------------------------
            
            const CACHE_NAME = "test";
                        
            const RESOURCE_FILES = [
                "/",
                "/index.html",
            "/manifest.json",
                        
            ];
                        
            self.addEventListener("install", event => {
                event.waitUntil(
                    caches.open(CACHE_NAME).then(cache => {
                        return cache.addAll(RESOURCE_FILES);
                    })
                );
            });
                        
            self.addEventListener("fetch", event => {
                event.respondWith(
                    fetch(event.request).catch(() => {
                        return caches.match(event.request);
                    })
                );
            });
            """;

        assertEquals(expected, readOutput(outputDir, "pwa/service-worker.js"));
    }

    @Test
    void clearOutputDirectory() throws IOException {
        Files.writeString(new File(inputDir, "manifest.json").toPath(), "{}", UTF_8);
        Files.writeString(new File(inputDir, "index.html").toPath(), "<html />", UTF_8);
        Files.writeString(new File(inputDir, "new.txt").toPath(), "1234", UTF_8);

        File buildDir = new File(outputDir, "pwa");
        buildDir.mkdirs();
        Files.writeString(new File(buildDir, "old.txt").toPath(), "1234", UTF_8);

        config.getWebAppDir().set(inputDir.getAbsolutePath());
        config.getManifest().set(new File(inputDir, "manifest.json").getAbsolutePath());
        config.getCacheName().set("test");
        task.run(config);

        assertTrue(new File(buildDir, "new.txt").exists());
        assertFalse(new File(buildDir, "old.txt").exists());
    }

    private String readOutput(File tempDir, String name) throws IOException {
        return Files.readString(new File(tempDir, name).toPath(), UTF_8);
    }
}
