name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container: colorizenl/colorize-ci
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Compile
        run: gradle compileJava
      - name: Unit tests
        run: gradle coverage -Pheadless=true
      - name: Archive test report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: build/reports
          retention-days: 3
